// app/layout.tsx

import type { Metadata } from "next";
import Nav from "./nav";
import Footer from "./footer";
import localFont from "next/font/local";
import "./globals.css";
import { BACKEND_IP } from "./config"; // Import from config.ts
import Auth from "./auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Remove BACKEND_IP export from here

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Auth />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
